### ISSUE TITLE
Bug with GetFilePath function

### ISSUE THREAD

**Issue by proxb** [proxb/PoshUSNJournal#5]
Via PowerShellGallery contact:

Hi,

I have found a bug in the module PoShUsnJournal. In the file PoShUsnJournal.psm1 at line 590: The function "GetFilePath" uses the parameter "PFileRefNumber" as an int64, but the USN-Journal itself uses Uint64! - the real problem is: [void][System.Runtime.InteropServices.Marshal]::WriteInt64($RefPtr, $PFileRefNumber) This does not work if you get a FileReferenceNumber thats too large for int64. Is it possible to write a bugfix?

best regards 
chirsitian hiebler

**Comment by proxb** [comment]
Made some updates to change the use of Int64 to use UInt64. Will include in next release.

**Comment by brconk** [comment]
This Bug still exists.  Changing the [uint64]$PFileRefNumber parameter to use Uint64 did not fix the issue because it is actually the [System.Runtime.InteropServices.Marshal]::WriteInt64($RefPtr, $PFileRefNumber)  that doesn't accept the Uint64 as the original poster said.  GetFilePath will still generate this when an FRN is too large.

NewUsnEntry : Cannot convert argument "val", with value: "9542846135421370560", for "WriteInt64" to type "System.Int64": "Cannot convert value "9542846135421370560" to type "System.Int64". Error: "Value was either too large or too small for an Int64.""
At C:\Program Files\Common Files\Modules\PoshUSNJournal\Scripts\Get-UsnJournalEntry.ps1:169 char:33
+ ... $UsnEntry = NewUsnEntry -UsnRecord $UsnRecord -DriveLetter $DriveLett ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [NewUsnEntry], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument,NewUsnEntry

Error is actually generated in the GetFilePath function line 615

 [void][System.Runtime.InteropServices.Marshal]::WriteInt64($RefPtr, $PFileRefNumber)

Would be great to get this fixed.
